console.log("start of a");
var a = " 101   ";
parseInt(a);
console.log(a);
parseFloat(a);
console.log(a);
Number(a);
console.log(a);
var a = +a;
console.log(a);
console.log("end of a");
console.log("start of b");
var b = "55";
parseInt(b);
console.log(b);
parseFloat(b);
console.log(b);
Number(b);
console.log(b);
var b = +b;
console.log(b);
console.log("end of b");
console.log("start of c");
var c = "402 Stevens";
parseInt(c);
console.log(c);
parseFloat(c);
console.log(c);
Number(c);
console.log(c);
var c = +c;
console.log(c);
console.log("end of c");
console.log("start of d");
var d = "Number 5 ";
parseInt(d);
console.log(d);
parseFloat(d);
console.log(d);
Number(d);
console.log(d);
var d = +d;
console.log(d);
console.log("end of d");
